### PR TITLE
fix: tolerate positive slippage

### LINKED ISSUE #1370: EVM: Swaps funded by external dex hop can exceed max
Due to positive slippage, swaps created near the max limit that are funded by an external DEX hop, e.g. USDT -> BTC can exceed our backend max amount. Possible solution: apply a `max(X sats, 2%)` buffer similar to what we are currently using as overpayment protection. Situation is different though, user is not actually overpaying, just being lucky. So we should be permissive.

### PR DESCRIPTION
**Pull request by michael1011**
Closes https://github.com/BoltzExchange/boltz-backend/issues/1370

Allow commitment swaps and chain swap renegotiation to accept positive slippage up to the configured overpayment tolerance.

## Summary by CodeRabbit

* **Documentation**
  * Added optional maxOverpaymentPercentage to commitment submission docs and clarified signature/amount constraints
  * Updated renegotiation guidance to reflect allowed overpayment within tolerance

* **New Features**
  * Introduced configurable positive-slippage tolerance for accepting overpayments
  * Locked amounts may now exceed previous maximal limits when within the configured tolerance

### CODE REVIEW

**Comment by michael1011** [comment]
@coderabbitai review

File: lib/service/Renegotiator.ts [hunk 1]
```diff
@@ -268,7 +271,14 @@ class Renegotiator {
...
+      swap.receivingData.amount! >
+      pair.limits.maximal +
+        getAllowedPositiveSlippageFromConfig(
+          pair.limits.maximal,
+          this.overPaymentConfig,
+        )
+    ) {
       throw Errors.EXCEED_MAXIMAL_AMOUNT(
         swap.receivingData.amount!,
         pair.limits.maximal,
```
Comment (kiocos) [inline lib/service/Renegotiator.ts:282]: should be maximal + tolerance

**Review by kiocos — CHANGES_REQUESTED** [review]

File: lib/service/Renegotiator.ts (hunk 1 above)
Comment (michael1011) [reply lib/service/Renegotiator.ts:282]: This is intentional. We don't want to advertize our soft limits

File: lib/swap/OverpaymentProtector.ts [hunk 2]
```diff
@@ -2,27 +2,60 @@ import type { OverPaymentConfig } from '../Config';
...
+export const getAllowedPositiveSlippageFromConfig = (
+  amount: number,
+  config?: OverPaymentConfig,
+  maxPercentageOverride?: number,
+): number =>
+  getAllowedPositiveSlippage(
+    amount,
+    resolvePositiveSlippageTolerance(config, maxPercentageOverride),
+  );
+
```
Comment (jackstar12) [inline lib/swap/OverpaymentProtector.ts]: We might aswell put all these into the `OverpaymentProtector` and pass that around - its only a wrapper around the config + logger anyways.

**Review by jackstar12 — APPROVED** [review]

**Review by maybeast — APPROVED** [review]
